services:
  - type: web
    name: umkmsitebuilder-api
    env: php
    rootDir: backend
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan storage:link && php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:6kYlO0Zz1Q5vM0o1Y9tV1vN2bK3xL4mP5qR6sT7uV8w=
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: umkmsitebuilder-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: umkmsitebuilder-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: umkmsitebuilder-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: umkmsitebuilder-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: umkmsitebuilder-db
          property: password

databases:
  - name: umkmsitebuilder-db
    databaseName: sitebuilder
    user: sitebuilder_user
